### ISSUE TITLE
Unable to create instances of AppID

### ISSUE THREAD

**Issue by s0uravd3** [IBM/platform-services-python-sdk#72]
We need instances of appId to be automated. Im using the ibm_platform_services  python package to do so.
```
ibmcloud catalog service-marketplace | grep appid
AdvancedMobileAccess-d6aece47-d840-45b0-8ab9-ad15354deeea            appid                                                      IBM                                     apidocs_enabled,disable_reclamation,eu_access,hipaa,ibm_created,security
```
I figured the id for appId is `AdvancedMobileAccess-d6aece47-d840-45b0-8ab9-ad15354deeea`  and I added `-lite` as suffix for **plan**

I then passed the same in the code
```
# Set the service URL
resource_controller_service.set_service_url('https://resource-controller.cloud.ibm.com')
resourceInstanceName = "testAppID3"
targetRegion = "us-south"
resourceGroup = "2e3eea217a314825a00530e806eaa23b"
resourcePlanId = "AdvancedMobileAccess-d6aece47-d840-45b0-8ab9-ad15354deeea-lite"
resource_instance = resource_controller_service.create_resource_instance(
  name=resourceInstanceName,
  target=targetRegion,
  resource_group=resourceGroup,
  resource_plan_id=resourcePlanId
).get_result()
print(json.dumps(resource_instance, indent=2))
```
but it fails
```
Traceback (most recent call last):
  File "appID.py", line 18, in <module>
    resource_instance = resource_controller_service.create_resource_instance(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ibm_platform_services/resource_controller_v2.py", line 235, in create_resource_instance
    response = self.send(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ibm_cloud_sdk_core/base_service.py", line 245, in send
    raise ApiException(
ibm_cloud_sdk_core.api_exception.ApiException: Error: An error occurred while retrieving resource catalog, Code: 404 , X-global-transaction-id: bss-7602b1accac92ea1
```

**Comment by s0uravd3** [comment]
I did a bit of reverse engineering to find what's the resource_plan_id and this is what I found. For AppID the `free` plan `resource_plan_id` and other details looks like : 

```
      "name": "App ID-y8",
      "region_id": "us-south",
      "account_id": "cf754e98bbe946c8ba3329b6cc4483bc",
      "reseller_channel_id": "",
      "resource_plan_id": "c0258a22-160a-403b-845d-1588ad61204c",
      "resource_group_id": "2e3eea217a314825a00530e806eaa23b"
```

On putting the value as `c0258a22-160a-403b-845d-1588ad61204c` it worked.

Closing the issue.
